- name: "Restart SWAG container"
  community.docker.docker_container:
    name: swag
    state: started
    restart: true

- name: "Restart SSH daemon"
  become: true
  ansible.builtin.systemd:
    name: sshd
    state: restarted
